# Historia del Capitán América

Nombre *Auténtico: Steven "Steve" Rogers*
Ocupación: *Heroe, ex-soldado de la Segunda Guerra Mundial, Vengador*
Otros "Alias": *"Capi", "Cabeza Alada", el Capitán, Steven Grant Rogers*

## Historia

Steve Rogers nació durante la Depresión y creció, convirtiéndose en un joven débil en una familia pobre. Su padre murió cuando él era un niño; su madre, durante la adolescencia de Steve. Horrorizado ante un noticiario que mostraba a los nazis en Europa, Rogers intentó alistarse en el ejército. En cambio, debido a su fragilidad y su malestar, fue rechazado. Oyendo la súplica fervorosa del chico para que lo aceptaran, el General Chester Phillips del Ejército de USA ofreció a Rogers la oportunidad de formar parte de un experimento especial llamado Operación Renacimiento. Rogers aceptó y fue llevado a un laboratorio secreto en Washington D.C., donde fue presentado al Dr. Abraham Erskine (nombre clave: Profesor Reinstein), el creador de la fórmula del Supersoldado.

Después de semanas de pruebas, a Rogers se le administró el suero del Supersoldado. Dándole parte del compuesto de modo intravenoso y otra parte oralmente, Rogers fue bombardeado por "vita-rayos", una combinación especial de longitudes de onda exóticas (en 1941) de radiación diseñadas para estabilizar y acelerar el efecto del suero en su cuerpo. Steve Rogers salió de la cámara de los vita-rayos con un cuerpo tan perfecto como puede ser sin dejar de ser humano. Un espía nazi que había observado el experimento asesinó al Dr. Erskine minutos después de su conclusión. Erskine murió sin transcribir totalmente la fórmula del Supersoldado a papel, convirtiendo a Steve Rogers en el único beneficiario de su genio.

Entonces, Rogers fue sometido a un programa intensivo de entrenamiento físico y táctico, enseñándole gimnasia, combate cuerpo a cuerpo y estrategia militar. Tres meses después, se le dio su primera misión, detener al agente nazi llamado Cráneo Rojo. Para ayudarle a convertirse en una contrapartida de Cráneo Rojo, a Rogers se le dio el traje rojo, blanco y azul del Capitán América.

Durante la guerra, sirvió como símbolo de libertad y como el operario especial más efectivo de América. Entonces, durante los últimos días de la guerra, intentó detener un avión cargado de bombas, lanzado por el técnico nazi Barón Heinrich Zemo, cuando el avión explotó, matando a su compañero Bucky y tirando al Capitán, indemne, a las heladas aguas árticas. La fórmula del Supersoldado impidió la cristalización de los fluidos corporales del Capitán América, permitiéndole entrar en un estado de animación suspendida. Décadas después, fue rescatado por el grupo recientemente formado, de nombre los Vengadores, y se convirtió en una piedra angular del equipo. Con su poder sin haber disminuido, el Capitán América sigue siendo un símbolo de libertad y justicia.

Más tarde, una comisión del gobierno de los Estados Unidos dio a Rogers un ultimátum; servirles a ellos exclusivamente o dejar de ser el Capitán América. Rogers, sintiendo que trabajar sólo para el gobierno obstruiría su misión, se negó y les dio su escudo y su uniforme. El gobierno golpeó a Rogers con un entredicho jurídico que le prohibió usar el nombre "Capitán América" ni un disfraz que fuera rojo, blanco y azul. Rogers adoptó un disfraz rojo, blanco y negro, de estilo similar a su uniforme original, y se hizo llamar "el Capitán". Poco después, en cambio, Rogers recuperó eventualmente su verdadera identidad.
